all:
	cd /home/ubuntu/Programming/GameLink/Development/1.4/classes/algorithms; \
	rm -f *
	cd /home/ubuntu/Programming/GameLink/Development/1.4/source; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes algorithms/*.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/game/Cram.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/game/CramGameBoard.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/game/GameBoard.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/main/CramTournamentSimulator.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/connect/Link.java; \
	javac -Xlint:unchecked -d /home/ubuntu/Programming/GameLink/Development/1.4/classes  org/gamelink/tournament/Match.java; \
	cd /home/ubuntu/Programming/GameLink/Development/1.4/classes; \
	java org.gamelink.main.CramTournamentSimulator